### ISSUE TITLE
Error installing HyphenateChat

### ISSUE THREAD

**Issue by Zeehshan** [AgoraIO/Agora-Chat-API-Examples#39]
agora_chat_sdk: ^1.0.7+1

I am getting error 
<img width="602" alt="Screenshot 2022-09-11 at 3 45 54 PM" src="https://user-images.githubusercontent.com/25202051/189523361-69eabb1f-2a4b-4417-8ef7-b6189e1fe55a.png">

Anyone please solution ?

**Comment by Zeehshan** [comment]
okay let me try it, but i am sure that's not the issue

**Comment by Zeehshan** [comment]
@plutoless i am getting still same error.

**Comment by githubzhaoliang** [comment]
@Zeehshan could you post your Podfile?

**Comment by zjc19891106** [comment]
@Zeehshan Can you show me your podfile?

**Comment by Zeehshan** [comment]
@plutoless  thanks i get resolved, 

> @Zeehshan this looks like a network issue. Seems the connection was interrupted. Please kindly check if you are using any proxy tools or switch your network.

Thanks i think that was issue i were trying from 3 days, i tried to called pod install again and again and get resolved it.

**Comment by Zeehshan** [comment]
i have another question that i need to call loginWithAgoraToken every time when i opens the app or just once time when user loggedIn to the app as well as i can call also loginWithAgoraToken ?

**Comment by plutoless** [comment]
you will need to re-login every time you restart the app

**Comment by Zeehshan** [comment]
List<ChatConversation> list =
      await ChatClient.getInstance.chatManager.getConversationsFromServer();

How can i get realtime ChatConversation ?

**Comment by plutoless** [comment]
@githubzhaoliang @zjc19891106 please help take a look

**Comment by dujiepeng** [comment]
@Zeehshan 
https://docs.agora.io/en/agora-chat/agora_chat_manage_message_flutter?platform=Flutter
List<ChatConversation> list = await ChatClient.getInstance.chatManager.loadAllConversations();
Use this method to get a list of conversations in the database.
After receiving a new message event, you can obtain it again.

**Comment by Zeehshan** [comment]
> @Zeehshan https://docs.agora.io/en/agora-chat/agora_chat_manage_message_flutter?platform=Flutter List list = await ChatClient.getInstance.chatManager.loadAllConversations(); Use this method to get a list of conversations in the database. After receiving a new message event, you can obtain it again.


New message event called in chat room, not in conversation list. in conversation list how can i get message event ?

**Comment by Zeehshan** [comment]
I have one more issue, i am sending vide in agora chat, on android side its loading video from remote path but on ios side its giving me error, its looks like for IOS agora video remote path not working.
Also thumbnail of the vide during creation of message also not working.
As agora sdk automatically downloads thumbnail that also not working.
Anyone face this issue ?

**Comment by dujiepeng** [comment]
Can you provide the download path?
