### ISSUE TITLE
Flutter Demo Setup: SDK has not initialize

### ISSUE THREAD

**Issue by dagyu** [AgoraIO/Agora-Chat-API-Examples#72]
I followed the instructions outlined in the README file to set up user authentication for my chat application. Here are the steps I followed:

- Enabled chat functionality.
- Created two user profiles.
- Obtained the AppKey from the chat section.
- Generated the Chat User Temporary Token.

However, I'm encountering an issue when attempting to sign in from the app. It displays the following error message: `Login failed, Code: 1, Description: SDK has not initialized.`

This error is preventing me from using the application as intended. I would greatly appreciate any assistance in resolving this issue.

The attached screenshot illustrates the sections where I obtained the App Key and Token.

<img width="677" alt="Screenshot 2023-09-13 at 16 51 52" src="https://github.com/AgoraIO/Agora-Chat-API-Examples/assets/23644210/226db897-1382-482a-81bc-7576ebddf072">

Please let me know if you need any further information or clarification. Thank you in advance for your help!

**Comment by dagyu** [comment]
Code from example https://github.com/AgoraIO/Agora-Chat-API-Examples/blob/d82dcce005f3b82b32569ab948f95bf2daee3227/chat_flutter/pubspec.yaml#L37 use 1.1.0 agora_chat_sdk version, updating to 1.1.1 fix the problem.

**Comment by dujiepeng** [comment]
@dagyu  thanks, fixe in https://github.com/AgoraIO/Agora-Chat-API-Examples/pull/73
