### ISSUE TITLE
package is not working with 0.72 version

### ISSUE THREAD

**Issue by Shweta-UMR** [AgoraIO/Agora-Chat-API-Examples#78]
Hello,
I have integrated code which is working fine with 0.68 but when i tried to update package with 0.72 version it is failing with following error.

Execution failed for task ':react-native-agora-chat:configureCMakeDebug[arm64-v8a]

thanks

**Comment by Shweta-UMR** [comment]
@AsteriskZuo thanks for response.. 
I tried with new fresh project and facing same issue for "Execution failed for task ':react-native-agora-chat:configureCMakeDebug[arm64-v8a]". 
Below is my dependency code

` "dependencies": {
    "agora-react-native-rtm": "^1.5.1",
    "agora-rn-uikit": "^5.0.2",
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-agora": "^4.2.6",
    "react-native-agora-chat": "^1.2.0",

  },`

thanks..

**Comment by AsteriskZuo** [comment]
> @AsteriskZuo thanks for response.. I tried with new fresh project and facing same issue for "Execution failed for task ':react-native-agora-chat:configureCMakeDebug[arm64-v8a]". Below is my dependency code
> 
> ` "dependencies": { "agora-react-native-rtm": "^1.5.1", "agora-rn-uikit": "^5.0.2", "react": "18.2.0", "react-native": "0.72.7", "react-native-agora": "^4.2.6", "react-native-agora-chat": "^1.2.0",
> 
> },`
> 
> thanks..

Please try the sample code `https://github.com/AsteriskZuo/RNTestIMExample072.git` and see if there are any problems. Compare the problem.

**Comment by AsteriskZuo** [comment]
https://github.com/expo/expo/issues/20123

**Comment by AsteriskZuo** [comment]
This should be a react-native related question. You can search it.

**Comment by AsteriskZuo** [comment]
Please try to install cmake 3.10.2 version.

**Comment by Shweta-UMR** [comment]
@AsteriskZuo thanks for the help.. issue is resolved, issue is showing due to the spaces in my parent directory.
